import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <div className="bg-blue-700 text-blue-50 gap-12 pl-20 text-5xl " >
      <Link className="mr-6 " href={"/"}>Home</Link>
      <Link className="mr-6 " href={"/about"}>About </Link>
      <Link className="mr-6 " href={"/contact"}>contact</Link>
      <Link className="mr-6 " href={"/users"}>user</Link>
     </div>

        {children}
      </body>
    </html>
  );
}
